apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/berringo/berry-wanmeng-app
  newName: quay.io/berringo/berry-wanmeng-app
  newTag: 405f7abac2356f452a8de2ee54b785a03757409ef6e8daa4c6822e75e19f1790
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/berringo/berry-wanmeng-app
  newTag: c34b6efbefd03c21d1075a23ffb85ce36f610f46
commonLabels:
  app: nextjs-app
  app.kubernetes.io/instance: nextjs-app
  app.kubernetes.io/name: nextjs-app
